### ISSUE TITLE
Document project setup and meta-information

### ISSUE THREAD

**Issue by blauks** [IT2901-SINTEF01/frontend#1]
## README.md
- [x] Title
- [x] (Logo and stats if we are feeling cheeky)
- [x] Two-three sentences about the project
- [x] How to set up the project 
- [x] How to run the project

## LICENSE
- [x] Add Apache 2 license 

## Wiki
- [x] Frontpage with links to subpages
- [x] Document CI
- [x] Document architecture
- [x] Folder structure
- [x] Testing
- [x] Code style

**Comment by blauks** [comment]
License added directly to master 🙂

**Comment by FredrikAugust** [comment]
Updated issue with more information. 

@IT2901-SINTEF01/police any input here regarding extra information?

**Comment by FredrikAugust** [comment]
I see 

> TBD

in the [wiki pages about testing and CI](https://github.com/IT2901-SINTEF01/frontend/wiki/Continous-Integration). These decisions have been made as far as I'm aware.

If content will be added at a later date, use "TK"[0].

[0] https://en.wikipedia.org/wiki/To_come_(publishing) 


--------

Furthermore @blauks, any ETA on this? Would be great if we could have it done by the day if possible – and even better if it could be resolved before 12:00 PM.

**Comment by blauks** [comment]
I will probably be able write the pages within today👍

**Comment by FredrikAugust** [comment]
Perfect.

**Comment by FredrikAugust** [comment]
Is this done?

**Comment by blauks** [comment]
The issue as a whole is not done yet. Is the contributing.md file really necessary? We basically mention all the relevant things in the wiki.

**Comment by FredrikAugust** [comment]
No. 

Documenting the architecture, however, is;) Feel free to close the issue once you're done!

**Comment by emilom** [comment]
I will write about architecture now. Should I mostly write about React, GraphQL/Apollo?

**Comment by FredrikAugust** [comment]
Important subjects:
- GraphQL+Apollo
- Storybook
- Caching in Apollo? Might have to do some research here. It's very easy to set up

**Comment by emilom** [comment]
Will we be using Apollo for state management as well?

**Comment by FredrikAugust** [comment]
This is something you may decide internally in @IT2901-SINTEF01/frontend, but I assume it will suffice in the foreseeable future.

**Comment by blauks** [comment]
Finished!
