### ISSUE TITLE
Investigate code structure and attempt to lower complexity

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#117]
### Description
As of now, there's quite a lot of data being passed around without any structure in the communication. Sometimes the data comes from local storage, sometimes it's from an enum, object, array, array of arrays, et cetera.

The PR associated with this issue should attempt to minimise the state held in the application in favor of simpler functional components and function composition. See attached Notion doc for some jumbled notes.

### Subtasks
- [ ] Clean up available visualisation retrieval
- [ ] Clean up data source parameter generation (in collaboration with @fredrikbw)
- [ ] Rewrite data structures
- [ ] Make application less complex

### Related sources
- [Extra information and theory crafting](https://www.notion.so/Demystifying-Data-Visualisations-47cc05eb8f684ae9a2ddf0fcc37a5dc9)
