### ISSUE TITLE
Wireframes in Figma

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#20]
### Description

Create wireframes in Figma. Post link or images here when done.

### Subtasks
- [x] Assign project, milestone, labels and assignees
- [x] Create figma project and share with team
- [x] Create wireframe for dashboard

**Comment by FredrikAugust** [comment]
Work will begin on this today at 12:00 PM during the meeting.

**Comment by FredrikAugust** [comment]
@IT2901-SINTEF01/ux-design Could you make sure this is done by the end of the day (2021/02/16) and a link to the figma is included in the wiki under a page called "Design"?

**Comment by thomran** [comment]
On it!

**Comment by FredrikAugust** [comment]
[Wiki](https://github.com/IT2901-SINTEF01/frontend/wiki).
