### ISSUE TITLE
Write about decisions directed towards visx

### ISSUE THREAD

**Issue by blauks** [IT2901-SINTEF01/frontend#21]
### Subtasks
- [x] Why we chose it
- [x] Why is it better to use visx than other competitors?
- [x] How we will use it

### Related sources
- https://airbnb.io/visx/

**Comment by emilom** [comment]
I have written a short wiki page now. Please have a look and write some feedback here :)

**Comment by FredrikAugust** [comment]
Looks good to me ✅

**Comment by blauks** [comment]
I fixed up in some minor spelling mistakes. You write both visx and Visx, it would be nice if all of them either started with a capital letter or lowercase. You can choose. _The tools are divided into main and backup._ maybe this could be reworded into something like _We have decided to go for one library as the main choice, and have also selected a backup library if needed._

**Comment by FredrikAugust** [comment]
Good catch. If you feel the wording is a bit clunky, feel free to rewrite it, @blauks. I closed it as I wanted to avoid spending a lot of time on this.

I will leave it to you to follow up on this issue, and it would be great if it were resolved before 12:00 PM today as focus will shift towards Figma for the frontend team.

**Comment by FredrikAugust** [comment]
Regarding stuff like visx vs Visx. If you notice an inconsistency; google the library and make a decision. The important part is consistency – as you pointed out, so making _a_ choice is important than _which_ choice.

Interesting literature regarding this mentality;
- https://www.ted.com/talks/patrick_mcginnis_how_to_make_faster_decisions

**Comment by emilom** [comment]
Thanks guys <3
