### ISSUE TITLE
Create a fitting visualisation for MetAPI Compact

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#29]
### Description
For the MVP of the dashboard, we need a fitting visualisation.

The visualisations should take one data format, which is fitting for that visualisation. So for a bar chart, you may want `{ x: [1, 2, 3], y: [4, 5, 6] }` &c.

### Subtasks
- [x] Create visualisation for MetAPI Compact data
- [x] Add visualisation to `atoms` folder (if #26)
- [x] Add storybook example with visualisation component and the test data created in #27

### Related sources
- #27

**Comment by emilom** [comment]
Isn’t a graph more Molecule than Atom?

**Comment by FredrikAugust** [comment]
We can discuss this in the meeting tomorrow.
