### ISSUE TITLE
Create dashboard organism

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#30]
### Description
Create a dashboard component which supports multiple child components (visualisations)

### Subtasks
- [x] Create `Dashboard` organism
- [x] Create sensible component which supports displaying multiple visualisation (might be useful to take a look at React children and `props.children`)
- [x] Decide how you should determine what data should be passed to what component. Do you wish to create very minimal wrapper components (molecules) which simply feed data into the respective visualisations (atoms)? I would recommend creating some examples and evaluating the different approaches. Feel free to send me a message if you want input or have any questions. **The decision should be documented in the wiki.**
- [x] Set a standard for how data transformation between raw data source and visualisation component input should be made. Perhaps create a generic type for this which ties into a prop to the visualisation component?

E.g.
```typescript
const rawMetApiDataToBarChar: (rawData: MetApiData) => BarChartProps['data'] = (rawData) => {
  // ...
}
```

### Related sources
- Depends on #26
- https://reactjs.org/docs/composition-vs-inheritance.html#containment
