### ISSUE TITLE
Create atom for loading and error

### ISSUE THREAD

**Issue by emilom** [IT2901-SINTEF01/frontend#50]
### Description
We need custom atoms for loading and errors which can be displayed when fetching data from the backend. 

### Subtasks
- [x] Create atom for loading as designed in #32 
- [x] Create atom for error as designed in #32
- [x] Create atom for cases where GraphQL didn't fetch any data (as designed in #32)
- [x] Implement atoms in DataWrapper.tsx and Dashboard.tsx

**Comment by emilom** [comment]
We will be using the `Spinner` component from [evergreen](https://evergreen.segment.com/components/spinner) as atom for loading.

**Comment by emilom** [comment]
Use `InlineAlert` for error message. Found [here](https://evergreen.segment.com/components/alert)
