### ISSUE TITLE
Create data source selection page

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#53]
### Description
Good morning!

Next up, we need a page where the user can select what data source they wish to use for their visualisation.

In this issue, you only need to implement the page. You **do not** need to wire it up to a global store for handling selection of data sources.

### Subtasks
- [x] Create data source selection page
- [x] Retrieve data about available data sources from backend using GraphQL
- [x] Create buttons (useless ones) for adding data sources
