### ISSUE TITLE
Test adding data visualisations with Cypress

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#57]
### Description
Wow! A complete e2e test!

You should test that adding a data visualisation and navigating between the relevant pages works as expected.

### Subtasks
- [x] Test navigation with 404s as well
- [x] Test adding visualisation
- [x] Test deleting visualisation
