### ISSUE TITLE
Add vercel link to README and explain it in wiki

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#60]
### Description
Read title of issue.

### Subtasks
- [x] Explain in wiki
- [x] Add description in wiki of what it does
- [x] Add badge? ![Deployment badge](https://img.shields.io/github/deployments/it2901-sintef01/frontend/Production?label=Production%20deployment)

```markdown
![Deployment badge](https://img.shields.io/github/deployments/it2901-sintef01/frontend/Production?label=Production%20deployment)
```

### Related sources
- https://vercel.com/it2901-sintef01/frontend

**Comment by blauks** [comment]
Done :simple_smile:
