### ISSUE TITLE
Display available visualisations on the visualisation selection page

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#84]
### Description
This is actually a bit more work than illustrated by the title.

The backend metadata field returns a set of visualisations which have a `type` field, which we can map to different component types (e.g. `ThresholdChart`, `BarChart`, &c).

We need to use this information, alongside the information regarding what data source we are working with to retrieve the correct `mappingFunction`, map the data to the correct format, and inject it into the visualisation. This requires some changes to the way the mapping function is retrieved today.

With this issue (and corresponding PR) you should be able to view the different visualisations available to the data source.

#### Some considerations
- The `visualisation` object from the backend includes some metadata which should be passed to the visualisation (e.g. `name`, `axesName` &c)

### Subtasks
- [ ] Map `visualisation['type']` to chart type
- [ ] Map `visualisation['type']` to mapping function (with data source added to the equation)
- [ ] Generate "faked" visualisations on the selection page

### Additional information
This issue does not include the actual mapping of real data to the different visualisations. That will be handled in another issue. This does however lay the foundation for that.
