### ISSUE TITLE
Move vercel to private account to avoid $ deficit

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#90]
### Description
Migrate to a private vercel account so we don't have to spend $.

### Subtasks
- [ ] Create private vercel setup
- [ ] Update CI/CD
- [ ] Update docs
- [ ] Update repository information link

**Comment by blauks** [comment]
I will try to achive the sponsorship [requirements](https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project) of Vercel

**Comment by Kpaubert** [comment]
This sounds like a good idea!
