### ISSUE TITLE
Couple of small tasks

### ISSUE THREAD

**Issue by Kpaubert** [IT2901-SINTEF01/frontend#91]
### Description
Some issues I found when testing out the frontend project

### Subtasks
- [x] Find a new favicon
- [x] Set a new title so it's not "React App"
- [x] Remove or add functionality for the information bubble
![image](https://user-images.githubusercontent.com/43110067/112629294-6c383a80-8e34-11eb-8d7d-fd896c8c5fdb.png)
- [x] When checking and uchecking the "Ingen text"-checkbox, it automatically selects the text. Perhaps add "user-select: none"
![image](https://user-images.githubusercontent.com/43110067/112629396-90941700-8e34-11eb-85ab-449a4ed4802a.png)

**Comment by FredrikAugust** [comment]
:awooga:
